### ISSUE TITLE
Generalization of prediction

### ISSUE THREAD

**Issue by michaelwitting** [michaelwitting/LipidNetworkPredictR#2]
Creation of network should not only be possible for C. elegans, but also for other species.
Therefore a generic input is required. An important factor is the order of reactions, because reactions depend on each other.
An object defining the order of reactions would be helpful.

**Comment by tnaake** [comment]
Hi @michaelwitting 

Is there a general ressource to find out in which species which reaction takes place?

Will it help to look at the acyl chains (disregarding the head groups) and define by this the reactions? Currently there is no acyl elongation reactions involved and chain lengths are currently fixed. If we could use this information and we "create" all species that contain these acyl chains we might not miss any reaction.

**Comment by michaelwitting** [comment]
Elongation and desaturation takes place on the fatty acid level. So one would need to define the input fatty acids as I have done. Reactions can be generally infered from genome scale metabolic models, like WormJam. More general reactions can be found at RheaDB (https://www.rhea-db.org/).
We could use reactions from there as input and a user would need to define which reactions are present (e.g. by RheaDB ID) and which fatty acids shall be used as input.
