### ISSUE TITLE
Check conversion from 3- to 2-acyl group species

### ISSUE THREAD

**Issue by michaelwitting** [michaelwitting/LipidNetworkPredictR#3]
For example the DG kinase reactions converts DGs to PAs.
Currently, `DG(16:0/16:0/0:0)` gets converted to `PA(16:0/16:0/0:0)`, but should be `PA(16:0/16:0)`.

**Comment by tnaake** [comment]
Hi @michaelwitting 

This should be fixed now with the commit. Please have a look on the unit tests for the reactions (for the more specialized one I do not know if they are actually correct).
